{% set name = "xia2" %}
{% set version = "3.17.0" %}
{% set version_parts = version.split('.') %}
{% set version_xy = version_parts[0] ~ '.' ~ version_parts[1] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xia2/xia2/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0b33fb5f8c20387fd397676ba30ff11a5681108d055f07fbe519e8545f11a52e
  folder: xia2
  patches:
    - multiplex_test_fix.diff
    - test_prot_k_multiwave_double_fix.diff

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install ./xia2 -vv
  entry_points:
    - dev.xia2.check_mosaic = xia2.cli.check_mosaic:run
    - dev.xia2.create_mask = xia2.cli.create_mask:run
    - dev.xia2.file_statistics = xia2.cli.file_statistics:run
    - dev.xia2.make_sphinx_html = xia2.cli.make_sphinx_html:run
    - dev.xia2.show_mask = xia2.cli.show_mask:run
    - dev.xia2.show_mtz_cells = xia2.cli.show_mtz_cells:run
    - xia2.ssx = xia2.cli.ssx:run
    - xia2.ssx_reduce = xia2.cli.ssx_reduce:run
    - xia2.add_free_set = xia2.cli.add_free_set:run
    - xia2.compare_merging_stats = xia2.cli.compare_merging_stats:run
    - xia2.delta_cc_half = xia2.cli.delta_cc_half:run
    - xia2.get_image_number = xia2.cli.get_image_number:run
    - xia2.html = xia2.cli.xia2_html:run_with_log
    - xia2.index = xia2.cli.index:run_with_log
    - xia2.integrate = xia2.cli.integrate:run_with_log
    - xia2.is_doing = xia2.cli.is_doing:main
    - xia2.ispyb_json = xia2.cli.ispyb_json:run
    - xia2.ispyb_xml = xia2.cli.ispyb_xml:run
    - xia2.merging_statistics = xia2.cli.merging_statistics:run
    - xia2.multiplex = xia2.cli.multiplex:run
    - xia2.npp = xia2.cli.npp:run
    - xia2.overload = xia2.cli.overload:run
    - xia2.plot_multiplicity = xia2.cli.plot_multiplicity:run
    - xia2.print = xia2.cli.print:run_with_log
    - xia2.rebatch = xia2.cli.rebatch:run_with_log
    - xia2.report = xia2.cli.report:run_with_log
    - xia2.rescale = xia2.cli.rescale:run_with_log
    - xia2.setup = xia2.cli.setup:run
    - xia2.small_molecule = xia2.cli.small_molecule:run
    - xia2.strategy = xia2.cli.strategy:run_with_log
    - xia2.table1 = xia2.cli.table1:run
    - xia2.to_shelx = xia2.cli.to_shelx:run
    - xia2.to_shelxcde = xia2.cli.to_shelxcde:run
    - xia2 = xia2.cli.xia2_main:run
    - xia2.cluster_analysis = xia2.cli.cluster_analysis:run  


requirements:
  host:
    - python >=3.9
    - pip
    - cctbx-base >=2023.10
    - dxtbx ={{ version_xy }}
    - dials ={{ version_xy }}
  run:
    - {{ pin_compatible('cctbx-base') }}
    - {{ pin_compatible('dxtbx', max_pin='x.x', lower_bound=version_xy) }}
    - {{ pin_compatible('dials', max_pin='x.x', lower_bound=version_xy) }}
    - python >=3.9
    - jinja2
    - pyyaml
    - tabulate

test:
  source_files:
    - xia2/tests
    - xia2/conftest.py
  imports:
    - xia2
  requires:
    - dials-data
    - pytest
    - pytest-mock
    - pip
  commands:
    - pytest xia2/tests/ --regression-full  # [not win]
    - pip check

about:
  home: https://github.com/xia2/xia2
  license: BSD-3-Clause
  license_family: BSD
  license_file: xia2/LICENSE
  summary: Automated reduction of X-Ray diffraction data
  description: |
    An expert system for automated reduction of X-Ray
    diffraction data from macromolecular crystals
  doc_url: https://xia2.github.io/
  dev_url: https://github.com/xia2/xia2

extra:
  recipe-maintainers:
    - jbeilstenedmands
    - ndevenish
